#!/bin/bash

sudo yum-config-manager \
  --add-repo \
  https://download.docker.com/linux/centos/docker-ce.repo # containerd.io

sudo yum update

# --------------------------- disable swap ---------------------------

sudo swapoff -a
sudo sed -i '/ swap / s/^/#/' /etc/fstab

# -------------------------------- nfs -------------------------------

sudo yum -y install nfs-utils
sudo systemctl enable --now nfs-server rpcbind

# ------------------------ containerd runtime ------------------------

sudo yum -y install containerd.io
containerd config default | sudo tee /etc/containerd/config.toml
sudo systemctl enable --now containerd

cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

# Setup required sysctl params, these persist across reboots.
cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

sudo sysctl --system

# -------------------------- disable selinux -------------------------

sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

# ------------------------- disable firewall -------------------------

sudo systemctl disable --now firewalld

# ---------------------------- kubernetes ----------------------------

cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
sudo systemctl enable --now kubelet

# ------------- stuff do after kubeadm init has been run -------------

# kubectl apply -f \
#    https://docs.projectcalico.org/v3.21/manifests/calico.yaml
