# -*- mode: ruby -*-
# vi: set ft=ruby :

disk = 'disk.vdi'
Vagrant.configure("2") do |config|
  ["control","node-1","node-2"].each do |name| # more later
    config.vm.define "#{name}" do |node|
      node.vm.box = "generic/alma8"
      node.vm.hostname = "#{name}"
      node.vm.provider "virtualbox" do |v|
          v.memory = 2048
          if name == "control"
            v.cpus = 2
            unless File.exist?(disk)
              v.customize [
                'createhd',
                '--filename', disk,
                '--variant', 'Fixed',
                '--size', 20 * 1024
              ]
            end
            v.customize [
              'storageattach', :id,
              '--storagectl', 'IDE Controller',
              '--port', 1,
              '--device', 0,
              '--type', 'hdd',
              '--medium', disk
            ]
          else
            v.cpus = 1
          end
      end
      node.vm.disk :disk, size: "10GB", primary: true
      node.vm.provision "shell", path: "provision"
      node.vm.provision "shell", path: "post"
    end
  end
end
