# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
  end
  config.vm.provision "shell", path: "provision"
  config.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx"
end
