#!/bin/bash

sudo yum-config-manager \
  --add-repo \
  https://download.docker.com/linux/centos/docker-ce.repo # containerd.io

sudo yum update

sudo yum -y install containerd.io
containerd config default | sudo tee /etc/containerd/config.toml
sudo systemctl enable --now containerd
