#!/usr/bin/env bash

## This scripts starts up minikube with "OIDC Connect" authentication strategy.
## https://kubernetes.io/docs/reference/access-authn-authz/authentication/

## Don't forget to add realm to the URL if using Keycloak
## Client key is not needed for public users in Keycloak
ISSUERURL="https://home.rwx.gg:8443/realms/k8s"
CLIENTID=minikube

# Make sure to put root CA (or interm root CA) into ~/.minikube/certs before
# running this for the first time so that it will be used to create ~/.minikube/ca.crt
# which will be referenced form the ~/.kube/config file under cluster.

minikube start \
    --extra-config=apiserver.oidc-issuer-url="$ISSUERURL" \
    --extra-config=apiserver.oidc-username-claim=preferred_username \
    --extra-config=apiserver.oidc-username-prefix=oidc: \
    --extra-config=apiserver.oidc-client-id="$CLIENTID"
