#!/bin/bash

./gettoken > /tmp/foo.json

kubectl config set-credentials minikube \
   --auth-provider=oidc \
   --auth-provider-arg=idp-issuer-url="https://home.rwx.gg:8443/realms/k8s" \
   --auth-provider-arg=client-id=minikube \
   --auth-provider-arg=idp-certificate-authority=/shared/ca.crt \
   --auth-provider-arg=id-token=$(jq -r .id_token /tmp/foo.json) \
   --auth-provider-arg=access-token=$(jq -r .access_token /tmp/foo.json) \
   --auth-provider-arg=refresh-token=$(jq -r .refresh_token /tmp/foo.json) 

