# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["VAGRANT_DEFAULT_PROVIDER"] = "virtualbox"
ENV["VAGRANT_EXPERIMENTAL"] = "disks"

Vagrant.configure("2") do |config|
  ["control","node1","node2"].each_with_index do |name, index|
    config.vm.define "#{name}" do |node|
      node.vm.box = "generic/alma8"
      node.vm.hostname = "#{name}"
      node.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.memory = 2048
        if name == "control"
          vb.cpus = 2
        else
          vb.cpus = 1 
        end
      end
      if name == "control"
          node.vm.disk :disk, size: "10MB", name: "extra"
      end
      node.vm.base_mac = nil
      node.vm.network "private_network", ip: "10.0.0.#{index + 2}"
      node.vm.provision "shell", path: "base"
      node.vm.provision "shell", path: "nfs"
      node.vm.provision "shell", path: "containerd"
      node.vm.provision "shell", path: "k8s"
    end
  end
end
